mywebsite/music/urls.py

from django.conf.urls import url ,include
from . import views

app_name = 'music'

urlpatterns = [
    url(r'^$', views.index,name='index'),
    url(r'^(?P<album_id>[0-9]+)/$', views.detail,name='detail'),
    url(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
]

mywebsite/mywebsite/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),

]

mywebsite/polls/urls.py
from django.conf.urls import url
from . import views
app_name='polls'
urlpatterns=[
    url(r'^$',views.index,name='index'),
    url(r'^(?P<question_id>[0-9]+)/$',views.detail,name="detail"),
    url(r'^(?P<question_id>[0-9]+)/results/$',views.result,name="result"),
    url(r'^(?P<question_id>[0-9]+)/vote/$',views.vote,name="vote"),

             ]


mywebsite/music/models.py
from django.db import models

# Create your models here.
class Album(models.Model):
    artist=models.CharField(max_length=250)
    album_title=models.CharField(max_length=500)
    genre=models.CharField(max_length=100)
    album_logo=models.CharField(max_length=1000)

    def __str__(self):
        return self.album_title+'--'+self.artist

class Song(models.Model):
    album=models.ForeignKey(Album,on_delete=models.CASCADE)
    file_type=models.CharField(max_length=10)
    song_title=models.CharField(max_length=250)
    is_fav=models.BooleanField(default=False)

    def __str__(self):
        return self.song_title + ' ' + str(self.album)

mywebsite/polls/models.py
import datetime
from django.db import models
from django.utils import timezone
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text


mywebsite/music/views.py
from django.http import Http404
from django.http import HttpResponse
from .models import Album,Song
from django.shortcuts import render,get_object_or_404
from django.template import loader


def index(request) :

    all_albums=Album.objects.all()


    return render(request,'music/index.html',{'all_albums': all_albums})


def detail(request, album_id):

    album=get_object_or_404(Album,pk=album_id)

    return render(request, 'music/detail.html', {'album': album})

def favorite(request,album_id):
    album=get_object_or_404(Album,pk=album_id)

mywebsite/polls/views.py

# Create your views here.
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.template import loader

from .models import Question
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    return render(request, 'polls/index.html', {'latest_question_list': latest_question_list})


from .models import Question
# ...
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})
def result(request,question_id):
    return HttpResponse("You r looking at results of %s"%question_id)
def vote(request,question_id):
    return HttpResponse("You voted for %s"%question_id)

mywebsite/music/templates/music/detail.html

<img src="{{album.album_logo}}">
     <h1>{{album.album_title}}</h1>
<h2>{{ album.artist }}</h2>

{% if error %}
<p><strong>{{ error }}</strong></p>
{% endif %}

<form action="{% url 'music : favorite' album.id %}" method="post">
    {% csrf_token %}
    {% for song in album.song_set.all %}
        <input type="radio" id="song{{forloop.counter}}" name="song" value="{{ song.id }}" />
        <label for="song{{forloop.counter}}">
          {{ song.song_title}}
          {% if song.is_fav %}
          <img src="https://www.bing.com/images/search?view=detailV2&ccid=zUQwlM8A&id=F568A42E8BC1FC887DD80FBF0F6CAA7BD122A003&thid=OIP.zUQwlM8AQx5Q88fxnBJcUQAQAQ&q=star++16x16&simid=608048056577625467&selectedIndex=2" />
          {% endif %}

        </label><br>
    {% endfor %}
    <input type="submit" value="Favourite">
</form>

mywebsite/music/templates/music/index.html

{% if all_albums%}
    <h3>All albums</h3>
    <ol>
        {% for album in all_albums %}
        <li><a href='{% url 'music:detail' album.id %}'>{{album.album_title}}</a></li>
        {% endfor %}
    </ol>
{% else%}
    <h3>No albums</h3>
{% endif %}

mywebsite/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>

mywebsite/polls/templates/polls/index.html
{% if latest_question_list %}
    <h2>Here are all the questions</h2>
   <h3> <ul>
    {% for question in latest_question_list %}
        <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}